[package]
name = "timesplit"
description = "The easy way to use multiple WakaTime compatible instances at once!"
version = "0.4.1"
edition = "2024"
license = "GPL-3.0"
readme = "README.md"
repository = "https://github.com/ImShyMike/timesplit"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
debug = false

[dependencies]
axum = { version = "0.8.7", features = ["tokio", "http1", "json"], default-features = false }
reqwest = { version = "0.12.24", features = ["json", "rustls-tls", "rustls-tls-native-roots", "gzip", "deflate", "brotli"], default-features = false }
tokio = { version = "1.48.0", features = ["rt-multi-thread", "macros"], default-features = false }
tracing = { version = "0.1.41", default-features = false }
tracing-subscriber = { version = "0.3.20", features = ["fmt", "env-filter", "ansi"], default-features = false }
serde = { version = "1.0.228", default-features = false }
serde_json = { version = "1.0.145", default-features = false }
base64 = { version = "0.22.1", default-features = false }
tower-http = { version = "0.6.6", features = ["trace"], default-features = false }
config = { version = "0.15.19", features = ["toml"], default-features = false }
dirs = { version = "6.0.0", default-features = false }
toml = { version = "0.9.8", features = ["display"], default-features = false }
bytes = { version = "1.11.0", default-features = false }
clap = { version = "4.5.53", default-features = false, features = ["derive", "std", "wrap_help"] }
rust-ini = { version = "0.21.3", default-features = false }
